version: '2.1'

services:
  users-db:
    container_name: users-db
    build: ./project/db
    ports: 
      - 3307:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=mysql+pymysql://root:root@users-db:3306/users_prod
      - DATABASE_TEST_URL=mysql+pymysql://root:root@users-db:3306/users_test

    command: gunicorn -b 0.0.0.0:5000 manage:app
    
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
  
  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    
    depends_on:
      users-service:
        condition: service_started
    
    links:
      - users-service
      


